### ISSUE TITLE
Ducks?

### ISSUE THREAD

**Issue by shibaInu45** [Leronus/mOres#5] opened 2022-01-02 10:17 UTC
Hello, I’m having an issue where ducks are just spawning by the hundreds and ruining all of my saves with constant lag. How do I fix this?  1.16

**Comment by Leronus** [comment] 2022-01-08 16:41
Hi @shibaInu45! 

First of, thank you for using my mod :)
I have been aware of this issue for a while now and have had difficulty fixing the bug.

My temporary solution thusfar was to disable spawning of the ducks in my mods config file named "mores-common.toml"
It is located in the config folder of your minecraft installation folder.

However, after a lot of checking and validating my code I believe I have finally found the problem. Please check if the problem is resolved with the latest release of mOres v2.3.2 [https://github.com/Leronus/mOres/releases/tag/v2.3.2]

You may download it here:
https://www.curseforge.com/minecraft/mc-mods/mores-by-its-infinite/files/3598559

**Comment by shibaInu45** [comment] 2022-01-08 17:22
Thank you so much for your reply! I’ll give that a download tomorrow and I’ll let you know if the problem is resolved. And thank you for letting me know how to do the config too.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shibaInu45** [comment] 2022-01-09 15:31
Hello, the update seems to working much better although I did have to /kill every living thing near me to kill the existing ones which was a simple fix in creative mode :) I have decided to turn them off completely which also works great. Thank you again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Closed as completed** 2022-01-10 02:38 UTC
Labels: bug
