### ISSUE TITLE
Minecraft version 1.20.1 Release v5.3.3 music disc bug

### ISSUE THREAD

**Issue by Lerrycapetime** [Leronus/mOres#16] opened 2023-10-11 14:57 UTC
The
Lemmino - Cipher music disc instantly consumes in juke box without playing anything and the disc cannot be retrieved, also seems the spawn rate might be a little too high since it spawned 5 of the same disc in one chest inside a mob spawner dungeon.

**Comment by Leronus** [comment] 2023-10-11 15:25
Thank you for bringing this issue to my attention.
I will test to see if I can reproduce the issue.
I'll keep you posted with any updates.

**Comment by Leronus** [comment] 2023-10-11 15:28
I've been able to reproduce the issue, good find. 
I think the music disc code changed when I updated from 1.19.4 to 1.20
That being said, I will try to fix this as we speak and release an update soon.
Thanks again for bringing this to my attention and for playing the mod :)

**Comment by Lerrycapetime** [comment] 2023-10-11 15:45
No problem! Awesome mod, me and my friends love it so far! only complaint is wish the ruby ore used the original texture from the game but that's not that big of a deal. I think I also found another bug with ducks, you are able to hear them from a pretty far distance.

**Comment by Leronus** [comment] 2023-10-11 15:52
What do you mean by the original texture from the game? As far as I know ruby ore has never been available in vanilla Minecraft but I could be wrong. I'm guessing you mean my old ruby texture from 1.12 / 1.16 versions?

As far as the ducks, I could not reproduce this issue. To me the distance seems fine, perhaps I could lower the volume a tiny bit but other than that it seemed pretty consistent in my testing. At what distance were you able to hear them as opposed to other mobs?

The music disc issue is now resolved. Will await your reply to see if any other fixes are needed, then I'll upload the new release.

Thanks for your compliments :)

**Comment by Lerrycapetime** [comment] 2023-10-11 16:10
About the main bug.
Thanks again, we'll download this update soon whenever ready!

About Ruby.
2:34 in this video
https://youtu.be/RzNvbyQLcLo?t=154
The ruby texture was actually an item used in game but got swapped with emerald later.

About Duck.
Oh that's strange with ducks, perhaps it could be something on my end with sound physics remastered or entity render distance? I'll do some deep diving with it later and see what I can discover, thanks!

**Comment by Leronus** [comment] 2023-10-11 16:33
This issue has been resolved in [Release v5.3.4](https://www.curseforge.com/minecraft/mc-mods/mores-by-its-infinite/files/4793694)
 

> About Ruby.

I prefer the current ruby texture over that one because it matches the structure of diamond and the other gems. I believe that in order to keep the mod consistent I'd have to change a lot of the textures I've personally grown very fond of. 
You could however, create a resourcepack with e.g. path “_assets/mores/textures/items/ruby.png_” with the texture(s) you'd like.

> About Duck.

Yes, it could very well be caused by a mod that modifies audio. Could also be that my duck entity is playing sound in a wrong way but I personally could not determine this. If you can discover more regarding this issue I would be happy to look into it :)

Kind regards,
**Leronus**

**Closed as completed by Leronus** 2023-10-11 16:33 UTC
Labels: bug
